---
include:
  - board: eyelash_corne
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_studio
  - board: eyelash_corne
    shield: settings_reset
    #snippet: zmk-usb-logging
 
